site_name: DataTorrent Documentation
theme: readthedocs
pages:
- DataTorrent RTS: index.md
- Demos:
    - Videos: demo_videos.md
    - Applications: demos.md
- Sandbox:
    - Welcome to the Sandbox: sandbox.md
    - Sandbox Demos: sandbox_demos.md
    - Sandbox Services: sandbox_services.md
- Applications:
    - dtIngest: dtingest.md
- Development and Tutorials:
    - Tutorials:
        - Top N Words:
            - Introduction: create.md
            - Development Environment: tutorial-topNwords/TopNWords-c1.md
            - Building in Java: tutorial-topNwords/TopNWords-c2.md
            - Building with dtAssemble: tutorial-topNwords/TopNWords-c3.md
            - Monitoring with dtManage: tutorial-topNwords/TopNWords-c4.md
            - Visualizing with dtDashboard: tutorial-topNwords/TopNWords-c5.md
            - Appendix: tutorial-topNwords/TopNWords-c6.md
        - Sales Dimenions: sales_dimensions.md
    - Apex Development Setup: apex_development_setup.md
    - Applications: coming_soon.md
    - Application Packages: application_packages.md
    - Configuration Packages: configuration_packages.md
    - Operators: coming_soon.md
    - Library Operators:
        - File splitter: operators/io/file_splitter.md
        - Block reader: operators/io/block_reader.md
        - File Input, S3, NFS: coming_soon.md
        - File Output: coming_soon.md
        - Deduper: coming_soon.md
        - HDHT: coming_soon.md
        - DimensionsStore: coming_soon.md
        - DimenstionComputation: coming_soon.md
        - KafkaInput: coming_soon.md
        - KafkaOutput: coming_soon.md
        - Solace: coming_soon.md
        - JMS: coming_soon.md
        - HBase: coming_soon.md
    - REST API: dtgateway_api.md
    - Scalable Design: coming_soon.md
- Platform:
    - RTS: rts.md
    - dtManage: coming_soon.md
    - dtAssemble: dtassemble.md
    - dtDashboard: dtdashboard.md
    - dtGateway: coming_soon.md
    - Apache Apex: apex.md
    - Apache Apex-Malhar: apex_malhar.md
- Deployment and Operations:
    - Quick Start: coming_soon.md
    - Installation: installation.md
    - Configuration: coming_soon.md
    - Security: dtgateway_security.md
    - dtCli: coming_soon.md
    - Troubleshooting: coming_soon.md
- Glossary: glossary.md
- Resources: additional_docs.md