site_name: DataTorrent Documentation
theme: readthedocs
pages:
- DataTorrent RTS: index.md
- Demos: 
    - Videos: demo_videos.md
    - Applications: demos.md
- Platform:
    - RTS: rts.md
    - dtAssemble: dtassemble.md
    - dtDashboard: dtdashboard.md
    - dtIngest: dtingest.md
- Creating Applications:
    - Creating with dtAssemble: create.md
    - Creating with Java: 'create_wordcount_app.md'
- Apache Apex:
    - Apex: apex.md
    - Apex-Malhar: apex_malhar.md
- Sandbox:
    - Welcome to the Sandbox: sandbox.md
    - Sandbox Demos: sandbox_demos.md
    - Sandbox Services: sandbox_services.md
- Additional Docs: additional_docs.md
